import AppKit
import Combine

/// Snapshot del origen tomado al inicio de poll().
struct CaptureSource {
    let name: String?
    let bundleID: String?
}

/// Monitorea el portapapeles, mantiene el historial y expone acciones.
final class ClipboardManager: ObservableObject {
    @Published private(set) var items: [ClipboardItem] = []

    private var timer: Timer?
    private var lastChangeCount: Int
    private var maxItems: Int { Settings.shared.maxItems }
    private let storage = Storage.shared
    private let settings = Settings.shared
    private let ownBundleID = Bundle.main.bundleIdentifier

    init() {
        lastChangeCount = NSPasteboard.general.changeCount
        items = storage.loadItems()
    }

    func start() {
        let t = Timer(timeInterval: 0.5, repeats: true) { [weak self] _ in self?.poll() }
        RunLoop.main.add(t, forMode: .common)
        timer = t
    }

    private func poll() {
        let pb = NSPasteboard.general
        guard pb.changeCount != lastChangeCount else { return }
        lastChangeCount = pb.changeCount
        let source = currentSource()                // origen ANTES del gate (el foco puede cambiar)
        guard !shouldIgnore(pb) else { return }
        capture(from: pb, source: source)
    }

    private func currentSource() -> CaptureSource {
        // Desactivado: atribuir el "origen" por la app frontal al momento del sondeo era poco
        // fiable (marcaba la app activa equivocada, p.ej. la que tenía el foco 0.5s después).
        CaptureSource(name: nil, bundleID: nil)
    }

    // MARK: - Filtro de privacidad

    private func shouldIgnore(_ pb: NSPasteboard) -> Bool {
        hasPrivacyMarker(pb) || isFrontmostAppExcluded()
    }

    private func hasPrivacyMarker(_ pb: NSPasteboard) -> Bool {
        guard let types = pb.types else { return false }
        let s = Set(types)
        if settings.ignoreConcealed     && s.contains(PasteboardPrivacyTypes.concealed)     { return true }
        if settings.ignoreTransient     && s.contains(PasteboardPrivacyTypes.transient)     { return true }
        if settings.ignoreAutoGenerated && s.contains(PasteboardPrivacyTypes.autoGenerated) { return true }
        return false
    }

    private func isFrontmostAppExcluded() -> Bool {
        guard let id = NSWorkspace.shared.frontmostApplication?.bundleIdentifier else { return false }
        if id == ownBundleID { return false }
        return settings.excludedBundleIDs.contains(id)
    }

    // MARK: - Captura

    private func capture(from pb: NSPasteboard, source: CaptureSource) {
        let remote = settings.detectRemoteSource
            && RemoteClipboardHeuristic.looksRemote(pb: pb, source: source,
                                                    captureSourceEnabled: settings.captureSource)
        if hasImageData(pb), let image = NSImage(pasteboard: pb) {
            addImage(image, source: source, remote: remote); return
        }
        if let str = pb.string(forType: .string),
           !str.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty {
            addText(str, source: source, remote: remote)
        }
    }

    private func hasImageData(_ pb: NSPasteboard) -> Bool {
        guard let types = pb.types else { return false }
        return types.contains(.tiff) || types.contains(.png)
            || types.contains(NSPasteboard.PasteboardType("public.jpeg"))
    }

    private func addText(_ text: String, source: CaptureSource, remote: Bool) {
        if let idx = items.firstIndex(where: { $0.kind == .text && $0.isVoiceNote != true && $0.text == text }) {
            var item = items.remove(at: idx)
            item.createdAt = Date()
            item.sourceName = source.name           // refrescar origen con la captura nueva
            item.sourceBundleID = source.bundleID
            item.isRemote = remote ? true : nil
            items.insert(item, at: 0)
        } else {
            let isCred = CredentialDetector.looksLikeCredential(text)
            let preview = isCred
                ? CredentialDetector.masked(text)   // no guardar el secreto en claro en el preview
                : String(text.prefix(160)).replacingOccurrences(of: "\n", with: " ").trimmingCharacters(in: .whitespaces)
            items.insert(ClipboardItem(kind: .text, text: text, preview: preview,
                                       sourceName: source.name, sourceBundleID: source.bundleID,
                                       isRemote: remote ? true : nil,
                                       isCredential: isCred ? true : nil), at: 0)
        }
        trimAndSave()
    }

    private func addImage(_ image: NSImage, source: CaptureSource, remote: Bool) {
        let fileName = "\(UUID().uuidString).png"
        storage.saveImage(image, fileName: fileName)
        let size = image.size
        let preview = "Imagen · \(Int(size.width))×\(Int(size.height))"
        items.insert(ClipboardItem(kind: .image, imageFileName: fileName, preview: preview,
                                   sourceName: source.name, sourceBundleID: source.bundleID,
                                   isRemote: remote ? true : nil), at: 0)
        trimAndSave()
    }

    /// Inserta una transcripción de voz como elemento de texto y la deja en el portapapeles.
    func addVoiceNoteText(_ text: String) {
        let clean = text.trimmingCharacters(in: .whitespacesAndNewlines)
        guard !clean.isEmpty else { return }
        let preview = "🎙 " + String(clean.prefix(160))
            .replacingOccurrences(of: "\n", with: " ")
            .trimmingCharacters(in: .whitespaces)
        items.insert(ClipboardItem(kind: .text, text: clean, preview: preview, isVoiceNote: true), at: 0)
        trimAndSave()
        copyToPasteboard(items[0])   // listo para pegar, sin re-capturar (actualiza lastChangeCount)
    }

    private func trimAndSave() {
        if items.count > maxItems {
            // Nunca borrar elementos fijados: conservar todos + los no-fijados más recientes.
            let pinned = items.filter { $0.pinned }
            var unpinned = items.filter { !$0.pinned }
            let allowed = max(0, maxItems - pinned.count)
            if unpinned.count > allowed {
                for it in unpinned[allowed...] where it.kind == .image {
                    if let f = it.imageFileName { storage.deleteImage(fileName: f) }
                }
                unpinned = Array(unpinned.prefix(allowed))
            }
            items = (pinned + unpinned).sorted { $0.createdAt > $1.createdAt }
        }
        storage.saveItems(items)
    }

    func applyMaxItems() { trimAndSave() }

    // MARK: - Acciones

    func copyToPasteboard(_ item: ClipboardItem) {
        let pb = NSPasteboard.general
        pb.clearContents()
        switch item.kind {
        case .text:
            if let t = item.text { pb.setString(t, forType: .string) }
        case .image:
            if let f = item.imageFileName, let img = storage.loadImage(fileName: f) {
                pb.writeObjects([img])
            }
        }
        lastChangeCount = pb.changeCount
    }

    func setClipboardText(_ text: String) {
        let pb = NSPasteboard.general
        pb.clearContents()
        pb.setString(text, forType: .string)
        lastChangeCount = pb.changeCount   // evita re-capturar la salida de Markdown/OCR como item nuevo
    }

    func extractText(from item: ClipboardItem) -> String? {
        guard item.kind == .image,
              let f = item.imageFileName,
              let img = storage.loadImage(fileName: f) else { return nil }
        return OCR.recognizeText(in: img)
    }

    func delete(_ item: ClipboardItem) {
        if item.kind == .image, let f = item.imageFileName { storage.deleteImage(fileName: f) }
        items.removeAll { $0.id == item.id }
        storage.saveItems(items)
    }

    func clearAll() {
        for it in items where it.kind == .image {
            if let f = it.imageFileName { storage.deleteImage(fileName: f) }
        }
        items.removeAll()
        storage.saveItems(items)
    }

    func togglePin(_ item: ClipboardItem) {
        guard let idx = items.firstIndex(where: { $0.id == item.id }) else { return }
        items[idx].pinned.toggle()
        trimAndSave()   // re-evaluar el recorte al desfijar (puede exceder maxItems)
    }

    /// Marca o desmarca un elemento como credencial (mini gestor).
    func toggleCredential(_ item: ClipboardItem) {
        guard let idx = items.firstIndex(where: { $0.id == item.id }) else { return }
        let nowCred = !(items[idx].isCredential == true)
        items[idx].isCredential = nowCred ? true : nil
        if let t = items[idx].text {   // regenerar el preview (enmascarar / desenmascarar)
            items[idx].preview = nowCred
                ? CredentialDetector.masked(t)
                : String(t.prefix(160)).replacingOccurrences(of: "\n", with: " ").trimmingCharacters(in: .whitespaces)
        }
        storage.saveItems(items)
    }
}

/// Heurística best-effort para "otro dispositivo" (NO hay API pública fiable de Universal Clipboard).
enum RemoteClipboardHeuristic {
    static func looksRemote(pb: NSPasteboard, source: CaptureSource, captureSourceEnabled: Bool) -> Bool {
        // Solo marcamos "otro dispositivo" si aparece el marcador fiable de Apple.
        // La heurística por "sin app de origen" daba falsos positivos (SecurityAgent, helpers…);
        // se elimina: preferimos NO marcar antes que marcar mal.
        pb.types?.contains(where: { $0.rawValue == "com.apple.is-remote-clipboard" }) == true
    }
}
