import AppKit
import Combine

/// Snapshot del origen tomado al inicio de poll().
struct CaptureSource {
    let name: String?
    let bundleID: String?
}

/// Monitorea el portapapeles, mantiene el historial y expone acciones.
final class ClipboardManager: ObservableObject {
    @Published private(set) var items: [ClipboardItem] = []

    private var timer: Timer?
    private var lastChangeCount: Int
    private var maxItems: Int { Settings.shared.maxItems }
    private let storage = Storage.shared
    private let settings = Settings.shared
    private let ownBundleID = Bundle.main.bundleIdentifier

    init() {
        lastChangeCount = NSPasteboard.general.changeCount
        items = storage.loadItems()
        reconcileVoiceNotesOnLoad()
        // Limpieza de huérfanos (audio/imágenes sin item, p.ej. tras un cierre a media transcripción).
        // Solo si hay items: items vacío también ocurre si items.json está corrupto/ilegible, y en ese
        // caso barrer borraría TODA la media (evitamos esa pérdida; los archivos siguen ahí para recuperar).
        if !items.isEmpty {
            storage.pruneOrphans(
                referencedAudio: Set(items.compactMap { $0.audioFileName }),
                referencedImages: Set(items.compactMap { $0.imageFileName }))
        }
    }

    /// Repara notas de voz que quedaron en "Transcribiendo…" (la app se cerró durante la transcripción):
    /// si conservan su audio, pasan a "sin transcripción" (recuperable); si no, se descartan.
    private func reconcileVoiceNotesOnLoad() {
        var changed = false
        for idx in items.indices where items[idx].isVoiceNote == true && items[idx].preview == Self.voiceTranscribing {
            if let af = items[idx].audioFileName, storage.audioExists(fileName: af) {
                items[idx].text = nil
                items[idx].preview = Self.voiceFailed
            } else {
                items[idx].audioFileName = nil   // marca para eliminar
            }
            changed = true
        }
        let before = items.count
        items.removeAll { $0.isVoiceNote == true && $0.preview == Self.voiceTranscribing && $0.audioFileName == nil }
        if changed || items.count != before { storage.saveItems(items) }
    }

    func start() {
        let t = Timer(timeInterval: 0.5, repeats: true) { [weak self] _ in self?.poll() }
        RunLoop.main.add(t, forMode: .common)
        timer = t
    }

    /// Pausa el monitoreo del portapapeles (p. ej. durante un import: evita escribir en el mismo
    /// directorio que la importación en segundo plano). Llamar en el hilo principal.
    func pauseMonitoring() { timer?.invalidate(); timer = nil }

    /// Reanuda el monitoreo. Reancla lastChangeCount para no capturar lo copiado durante la pausa.
    func resumeMonitoring() {
        guard timer == nil else { return }
        lastChangeCount = NSPasteboard.general.changeCount
        start()
    }

    private func poll() {
        let pb = NSPasteboard.general
        guard pb.changeCount != lastChangeCount else { return }
        lastChangeCount = pb.changeCount
        let source = currentSource()                // origen ANTES del gate (el foco puede cambiar)
        guard !shouldIgnore(pb) else { return }
        capture(from: pb, source: source)
    }

    private func currentSource() -> CaptureSource {
        // Desactivado: atribuir el "origen" por la app frontal al momento del sondeo era poco
        // fiable (marcaba la app activa equivocada, p.ej. la que tenía el foco 0.5s después).
        CaptureSource(name: nil, bundleID: nil)
    }

    // MARK: - Filtro de privacidad

    private func shouldIgnore(_ pb: NSPasteboard) -> Bool {
        hasPrivacyMarker(pb) || isFrontmostAppExcluded()
    }

    private func hasPrivacyMarker(_ pb: NSPasteboard) -> Bool {
        guard let types = pb.types else { return false }
        let s = Set(types)
        if settings.ignoreConcealed     && s.contains(PasteboardPrivacyTypes.concealed)     { return true }
        if settings.ignoreTransient     && s.contains(PasteboardPrivacyTypes.transient)     { return true }
        if settings.ignoreAutoGenerated && s.contains(PasteboardPrivacyTypes.autoGenerated) { return true }
        return false
    }

    private func isFrontmostAppExcluded() -> Bool {
        guard let id = NSWorkspace.shared.frontmostApplication?.bundleIdentifier else { return false }
        if id == ownBundleID { return false }
        return settings.excludedBundleIDs.contains(id)
    }

    // MARK: - Captura

    private func capture(from pb: NSPasteboard, source: CaptureSource) {
        let remote = settings.detectRemoteSource
            && RemoteClipboardHeuristic.looksRemote(pb: pb, source: source,
                                                    captureSourceEnabled: settings.captureSource)
        if hasImageData(pb), let image = NSImage(pasteboard: pb) {
            addImage(image, source: source, remote: remote); return
        }
        if let str = pb.string(forType: .string),
           !str.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty {
            addText(str, source: source, remote: remote)
        }
    }

    private func hasImageData(_ pb: NSPasteboard) -> Bool {
        guard let types = pb.types else { return false }
        return types.contains(.tiff) || types.contains(.png)
            || types.contains(NSPasteboard.PasteboardType("public.jpeg"))
    }

    private func addText(_ text: String, source: CaptureSource, remote: Bool) {
        if let idx = items.firstIndex(where: { $0.kind == .text && $0.isVoiceNote != true && $0.text == text }) {
            var item = items.remove(at: idx)
            item.createdAt = Date()
            item.sourceName = source.name           // refrescar origen con la captura nueva
            item.sourceBundleID = source.bundleID
            item.isRemote = remote ? true : nil
            items.insert(item, at: 0)
        } else {
            let isCred = CredentialDetector.looksLikeCredential(text)
            let preview = isCred
                ? CredentialDetector.masked(text)   // no guardar el secreto en claro en el preview
                : String(text.prefix(160)).replacingOccurrences(of: "\n", with: " ").trimmingCharacters(in: .whitespaces)
            items.insert(ClipboardItem(kind: .text, text: text, preview: preview,
                                       sourceName: source.name, sourceBundleID: source.bundleID,
                                       isRemote: remote ? true : nil,
                                       isCredential: isCred ? true : nil), at: 0)
        }
        trimAndSave()
    }

    private func addImage(_ image: NSImage, source: CaptureSource, remote: Bool) {
        let fileName = "\(UUID().uuidString).png"
        storage.saveImage(image, fileName: fileName)
        let size = image.size
        let preview = "Imagen · \(Int(size.width))×\(Int(size.height))"
        items.insert(ClipboardItem(kind: .image, imageFileName: fileName, preview: preview,
                                   sourceName: source.name, sourceBundleID: source.bundleID,
                                   isRemote: remote ? true : nil), at: 0)
        trimAndSave()
    }

    // MARK: - Notas de voz (audio guardado + transcripción en 3 pasos)

    static let voiceTranscribing = "🎙 Transcribiendo…"
    static let voiceFailed = "🎙 Nota de voz (sin transcripción · reproduce el audio)"
    static let voiceFailedNoAudio = "🎙 Nota de voz (no se pudo transcribir)"

    private static func voicePreview(_ clean: String) -> String {
        "🎙 " + String(clean.prefix(160))
            .replacingOccurrences(of: "\n", with: " ")
            .trimmingCharacters(in: .whitespaces)
    }

    /// changeCount del portapapeles al empezar cada nota: solo auto-pegamos su transcripción si el
    /// usuario NO copió nada distinto mientras transcribía (no pisar su portapapeles en 2º plano).
    private var voicePasteGuards: [UUID: Int] = [:]

    /// Crea el elemento de la nota de voz con su audio (placeholder "Transcribiendo…") y devuelve su id.
    @discardableResult
    func beginVoiceNote(audioFileName: String?, duration: Double?) -> UUID {
        let item = ClipboardItem(kind: .text, preview: Self.voiceTranscribing,
                                 isVoiceNote: true, audioFileName: audioFileName, audioDuration: duration)
        items.insert(item, at: 0)
        voicePasteGuards[item.id] = NSPasteboard.general.changeCount
        trimAndSave()
        return item.id
    }

    /// Vuelve a marcar un elemento como "Transcribiendo…" (reintento de una nota fallida).
    func markVoiceNoteTranscribing(id: UUID) {
        guard let idx = items.firstIndex(where: { $0.id == id }) else { return }
        items[idx].text = nil
        items[idx].preview = Self.voiceTranscribing
        storage.saveItems(items)
    }

    /// Rellena la transcripción. Solo la deja en el portapapeles si el usuario NO copió otra cosa
    /// mientras transcribía (evita pisar su portapapeles en segundo plano).
    func finishVoiceNote(id: UUID, text: String) {
        let clean = text.trimmingCharacters(in: .whitespacesAndNewlines)
        let canPaste = voicePasteGuards.removeValue(forKey: id).map { $0 == NSPasteboard.general.changeCount } ?? false
        guard let idx = items.firstIndex(where: { $0.id == id }) else {
            if !clean.isEmpty, canPaste { setClipboardText(clean) }   // el placeholder ya no existe: no perder el texto
            return
        }
        items[idx].text = clean.isEmpty ? nil : clean
        items[idx].preview = clean.isEmpty ? Self.voiceFailed : Self.voicePreview(clean)
        let item = items[idx]
        trimAndSave()
        if !clean.isEmpty, canPaste { copyToPasteboard(item) }   // solo si nada cambió el portapapeles
    }

    /// La transcripción falló: deja el elemento visible (con audio reproducible si lo hay) en vez de
    /// borrarlo en silencio, para que el usuario sepa qué pasó y pueda recuperarlo o eliminarlo.
    func failVoiceNote(id: UUID) {
        voicePasteGuards.removeValue(forKey: id)
        guard let idx = items.firstIndex(where: { $0.id == id }) else { return }
        items[idx].text = nil
        items[idx].preview = items[idx].audioFileName != nil ? Self.voiceFailed : Self.voiceFailedNoAudio
        storage.saveItems(items)
    }

    /// No se recorta: ni los fijados ni una nota de voz aún transcribiéndose (se perdería su audio/texto).
    private func isProtectedFromTrim(_ it: ClipboardItem) -> Bool {
        it.pinned || (it.isVoiceNote == true && it.preview == Self.voiceTranscribing)
    }

    private func trimAndSave() {
        if items.count > maxItems {
            let keep = items.filter { isProtectedFromTrim($0) }
            var trimmable = items.filter { !isProtectedFromTrim($0) }
            let allowed = max(0, maxItems - keep.count)
            if trimmable.count > allowed {
                for it in trimmable[allowed...] {
                    if it.kind == .image, let f = it.imageFileName { storage.deleteImage(fileName: f) }
                    if let af = it.audioFileName { AudioPlayer.shared.stopIfPlaying(af); storage.deleteAudio(fileName: af) }
                }
                trimmable = Array(trimmable.prefix(allowed))
            }
            items = (keep + trimmable).sorted { $0.createdAt > $1.createdAt }
        }
        storage.saveItems(items)
    }

    func applyMaxItems() { trimAndSave() }

    // MARK: - Acciones

    func copyToPasteboard(_ item: ClipboardItem) {
        let pb = NSPasteboard.general
        switch item.kind {
        case .text:
            guard let t = item.text, !t.isEmpty else { return }   // nota de voz sin texto: no tocar el portapapeles
            pb.clearContents(); pb.setString(t, forType: .string)
        case .image:
            guard let f = item.imageFileName, let img = storage.loadImage(fileName: f) else { return }
            pb.clearContents(); pb.writeObjects([img])
        }
        lastChangeCount = pb.changeCount
    }

    func setClipboardText(_ text: String) {
        let pb = NSPasteboard.general
        pb.clearContents()
        pb.setString(text, forType: .string)
        lastChangeCount = pb.changeCount   // evita re-capturar la salida de Markdown/OCR como item nuevo
    }

    func extractText(from item: ClipboardItem) -> String? {
        guard item.kind == .image,
              let f = item.imageFileName,
              let img = storage.loadImage(fileName: f) else { return nil }
        return OCR.recognizeText(in: img)
    }

    func delete(_ item: ClipboardItem) {
        if item.kind == .image, let f = item.imageFileName { storage.deleteImage(fileName: f) }
        if let af = item.audioFileName { AudioPlayer.shared.stopIfPlaying(af); storage.deleteAudio(fileName: af) }
        voicePasteGuards.removeValue(forKey: item.id)
        items.removeAll { $0.id == item.id }
        storage.saveItems(items)
    }

    /// Reemplaza el historial en memoria tras importar una copia de seguridad.
    func reload(_ newItems: [ClipboardItem]) {
        AudioPlayer.shared.stop()
        items = newItems
    }

    func clearAll() {
        AudioPlayer.shared.stop()
        voicePasteGuards.removeAll()
        for it in items {
            if it.kind == .image, let f = it.imageFileName { storage.deleteImage(fileName: f) }
            if let af = it.audioFileName { storage.deleteAudio(fileName: af) }
        }
        items.removeAll()
        storage.saveItems(items)
    }

    func togglePin(_ item: ClipboardItem) {
        guard let idx = items.firstIndex(where: { $0.id == item.id }) else { return }
        items[idx].pinned.toggle()
        trimAndSave()   // re-evaluar el recorte al desfijar (puede exceder maxItems)
    }

    /// Pone (o quita) la etiqueta/nombre de un elemento. El nombre es buscable y se muestra como título.
    func rename(_ item: ClipboardItem, to name: String) {
        guard let idx = items.firstIndex(where: { $0.id == item.id }) else { return }
        let trimmed = name.trimmingCharacters(in: .whitespacesAndNewlines)
        items[idx].name = trimmed.isEmpty ? nil : trimmed
        storage.saveItems(items)
    }

    /// Marca o desmarca un elemento como credencial (mini gestor).
    func toggleCredential(_ item: ClipboardItem) {
        guard let idx = items.firstIndex(where: { $0.id == item.id }) else { return }
        let nowCred = !(items[idx].isCredential == true)
        items[idx].isCredential = nowCred ? true : nil
        if let t = items[idx].text {   // regenerar el preview (enmascarar / desenmascarar)
            items[idx].preview = nowCred
                ? CredentialDetector.masked(t)
                : String(t.prefix(160)).replacingOccurrences(of: "\n", with: " ").trimmingCharacters(in: .whitespaces)
        }
        storage.saveItems(items)
    }
}

/// Heurística best-effort para "otro dispositivo" (NO hay API pública fiable de Universal Clipboard).
enum RemoteClipboardHeuristic {
    static func looksRemote(pb: NSPasteboard, source: CaptureSource, captureSourceEnabled: Bool) -> Bool {
        // Solo marcamos "otro dispositivo" si aparece el marcador fiable de Apple.
        // La heurística por "sin app de origen" daba falsos positivos (SecurityAgent, helpers…);
        // se elimina: preferimos NO marcar antes que marcar mal.
        pb.types?.contains(where: { $0.rawValue == "com.apple.is-remote-clipboard" }) == true
    }
}
