import AppKit
import Carbon.HIToolbox
import Combine

// MARK: - Pasteboard privacy marker types (nspasteboard.com convention)

enum PasteboardPrivacyTypes {
    static let concealed     = NSPasteboard.PasteboardType("org.nspasteboard.ConcealedType")
    static let transient     = NSPasteboard.PasteboardType("org.nspasteboard.TransientType")
    static let autoGenerated = NSPasteboard.PasteboardType("org.nspasteboard.AutoGeneratedType")
}

// MARK: - Global hotkey key combination (in Carbon space)

struct KeyCombo: Equatable {
    var keyCode: UInt32
    var carbonModifiers: UInt32

    /// Default panel shortcut: ⌘⇧E (Cmd+Shift+E). Avoids system defaults.
    static let defaultCombo = KeyCombo(keyCode: UInt32(kVK_ANSI_E),
                                       carbonModifiers: UInt32(cmdKey | shiftKey))
    /// Default voice shortcut: ⌘⇧I (Cmd+Shift+I).
    static let defaultVoiceCombo = KeyCombo(keyCode: UInt32(kVK_ANSI_I),
                                            carbonModifiers: UInt32(cmdKey | shiftKey))
    /// Default capture shortcut: ⌘⇧U (Cmd+Shift+U). A letter (not a number) so it doesn't clash with apps
    /// that hijack ⌘⇧2 (e.g. Loom), and to pair with ⌘⇧E / ⌘⇧I.
    static let defaultCaptureCombo = KeyCombo(keyCode: UInt32(kVK_ANSI_U),
                                              carbonModifiers: UInt32(cmdKey | shiftKey))
    /// Old capture default (⌘⇧2), used only to migrate anyone who has it persisted to ⌘⇧U.
    static let legacyCaptureCombo = KeyCombo(keyCode: UInt32(kVK_ANSI_2),
                                             carbonModifiers: UInt32(cmdKey | shiftKey))

    var isValid: Bool { carbonModifiers != 0 }

    var displayString: String {
        var s = ""
        if carbonModifiers & UInt32(controlKey) != 0 { s += "⌃" }
        if carbonModifiers & UInt32(optionKey)  != 0 { s += "⌥" }
        if carbonModifiers & UInt32(shiftKey)   != 0 { s += "⇧" }
        if carbonModifiers & UInt32(cmdKey)     != 0 { s += "⌘" }
        s += KeyCombo.keyName(for: keyCode)
        return s
    }

    static func keyName(for keyCode: UInt32) -> String {
        let map: [UInt32: String] = [
            UInt32(kVK_ANSI_A): "A", UInt32(kVK_ANSI_B): "B", UInt32(kVK_ANSI_C): "C",
            UInt32(kVK_ANSI_D): "D", UInt32(kVK_ANSI_E): "E", UInt32(kVK_ANSI_F): "F",
            UInt32(kVK_ANSI_G): "G", UInt32(kVK_ANSI_H): "H", UInt32(kVK_ANSI_I): "I",
            UInt32(kVK_ANSI_J): "J", UInt32(kVK_ANSI_K): "K", UInt32(kVK_ANSI_L): "L",
            UInt32(kVK_ANSI_M): "M", UInt32(kVK_ANSI_N): "N", UInt32(kVK_ANSI_O): "O",
            UInt32(kVK_ANSI_P): "P", UInt32(kVK_ANSI_Q): "Q", UInt32(kVK_ANSI_R): "R",
            UInt32(kVK_ANSI_S): "S", UInt32(kVK_ANSI_T): "T", UInt32(kVK_ANSI_U): "U",
            UInt32(kVK_ANSI_V): "V", UInt32(kVK_ANSI_W): "W", UInt32(kVK_ANSI_X): "X",
            UInt32(kVK_ANSI_Y): "Y", UInt32(kVK_ANSI_Z): "Z",
            UInt32(kVK_ANSI_0): "0", UInt32(kVK_ANSI_1): "1", UInt32(kVK_ANSI_2): "2",
            UInt32(kVK_ANSI_3): "3", UInt32(kVK_ANSI_4): "4", UInt32(kVK_ANSI_5): "5",
            UInt32(kVK_ANSI_6): "6", UInt32(kVK_ANSI_7): "7", UInt32(kVK_ANSI_8): "8",
            UInt32(kVK_ANSI_9): "9",
            UInt32(kVK_Space): "Espacio", UInt32(kVK_Return): "↩", UInt32(kVK_Tab): "⇥",
            UInt32(kVK_Escape): "⎋", UInt32(kVK_Delete): "⌫",
            UInt32(kVK_ANSI_Period): ".", UInt32(kVK_ANSI_Comma): ",",
            UInt32(kVK_ANSI_Slash): "/", UInt32(kVK_ANSI_Semicolon): ";"
        ]
        return map[keyCode] ?? String(format: "Tecla %02X", keyCode)
    }

    /// Suggested combinations to pick without recording (shown in Preferences).
    static let suggestions: [KeyCombo] = [
        KeyCombo(keyCode: UInt32(kVK_ANSI_E), carbonModifiers: UInt32(cmdKey | shiftKey)),   // ⌘⇧E
        KeyCombo(keyCode: UInt32(kVK_ANSI_I), carbonModifiers: UInt32(cmdKey | shiftKey)),   // ⌘⇧I
        KeyCombo(keyCode: UInt32(kVK_ANSI_U), carbonModifiers: UInt32(cmdKey | shiftKey)),   // ⌘⇧U (capture)
        KeyCombo(keyCode: UInt32(kVK_ANSI_Y), carbonModifiers: UInt32(cmdKey | shiftKey)),   // ⌘⇧Y
        KeyCombo(keyCode: UInt32(kVK_ANSI_M), carbonModifiers: UInt32(cmdKey | shiftKey)),   // ⌘⇧M
        KeyCombo(keyCode: UInt32(kVK_Space),  carbonModifiers: UInt32(optionKey)),           // ⌥Space
        KeyCombo(keyCode: UInt32(kVK_Space),  carbonModifiers: UInt32(optionKey | shiftKey)) // ⌥⇧Space
    ]
}

func cocoaToCarbonModifiers(_ flags: NSEvent.ModifierFlags) -> UInt32 {
    var carbon: UInt32 = 0
    if flags.contains(.command) { carbon |= UInt32(cmdKey) }
    if flags.contains(.shift)   { carbon |= UInt32(shiftKey) }
    if flags.contains(.option)  { carbon |= UInt32(optionKey) }
    if flags.contains(.control) { carbon |= UInt32(controlKey) }
    return carbon
}

// MARK: - Settings store (UserDefaults), single source of truth

final class Settings: ObservableObject {
    static let shared = Settings()
    private let d = UserDefaults.standard

    private enum K {
        static let maxItems   = "maxItems"
        static let keyCode    = "hotKeyCode"
        static let mods       = "hotKeyModifiers"
        static let autoPaste  = "autoPaste"
        static let concealed  = "privacy.ignoreConcealed"
        static let transient  = "privacy.ignoreTransient"
        static let autoGen    = "privacy.ignoreAutoGenerated"
        static let excluded   = "privacy.excludedBundleIDs"
        static let captureSrc = "captureSource"
        static let detectRem  = "detectRemoteSource"
        static let transModel = "transcriptionModel"
        static let geminiModel = "geminiModel"
        static let transLang  = "transcriptionLanguage"
        static let transVocab = "transcriptionVocabulary"
        static let aiProv     = "aiProvider"
        static let keyCode2   = "voiceHotKeyCode"
        static let mods2      = "voiceHotKeyModifiers"
        static let keyCode3   = "captureHotKeyCode"
        static let mods3      = "captureHotKeyModifiers"
        static let uiLang     = "uiLanguage"
    }

    @Published var maxItems: Int          { didSet { d.set(maxItems, forKey: K.maxItems) } }
    @Published var combo: KeyCombo        { didSet {
        d.set(Int(combo.keyCode), forKey: K.keyCode)
        d.set(Int(combo.carbonModifiers), forKey: K.mods)
    } }
    @Published var autoPaste: Bool        { didSet { d.set(autoPaste, forKey: K.autoPaste) } }
    @Published var ignoreConcealed: Bool  { didSet { d.set(ignoreConcealed, forKey: K.concealed) } }
    @Published var ignoreTransient: Bool  { didSet { d.set(ignoreTransient, forKey: K.transient) } }
    @Published var ignoreAutoGenerated: Bool { didSet { d.set(ignoreAutoGenerated, forKey: K.autoGen) } }
    @Published var excludedBundleIDs: [String] { didSet { d.set(excludedBundleIDs, forKey: K.excluded) } }
    @Published var captureSource: Bool    { didSet { d.set(captureSource, forKey: K.captureSrc) } }
    @Published var detectRemoteSource: Bool { didSet { d.set(detectRemoteSource, forKey: K.detectRem) } }
    @Published var transcriptionModel: String { didSet { d.set(transcriptionModel, forKey: K.transModel) } }
    /// Google Gemini model for transcription (configurable; previously hard-coded to "gemini-flash-latest").
    @Published var geminiModel: String { didSet { d.set(geminiModel, forKey: K.geminiModel) } }
    @Published var transcriptionLanguage: String { didSet { d.set(transcriptionLanguage, forKey: K.transLang) } }
    /// Context words / vocabulary (names, brands, jargon) sent to the transcriber so it spells them right.
    @Published var transcriptionVocabulary: String { didSet { d.set(transcriptionVocabulary, forKey: K.transVocab) } }
    /// AI provider for transcription: "openai" or "gemini".
    @Published var aiProvider: String { didSet { d.set(aiProvider, forKey: K.aiProv) } }
    @Published var voiceCombo: KeyCombo   { didSet {
        d.set(Int(voiceCombo.keyCode), forKey: K.keyCode2)
        d.set(Int(voiceCombo.carbonModifiers), forKey: K.mods2)
    } }
    @Published var captureCombo: KeyCombo { didSet {
        d.set(Int(captureCombo.keyCode), forKey: K.keyCode3)
        d.set(Int(captureCombo.carbonModifiers), forKey: K.mods3)
    } }
    @Published var uiLanguage: String     { didSet { d.set(uiLanguage, forKey: K.uiLang) } }

    /// Simple toggle that controls all three privacy filters at once.
    var ignoreSensitive: Bool {
        get { ignoreConcealed || ignoreTransient || ignoreAutoGenerated }
        set { ignoreConcealed = newValue; ignoreTransient = newValue; ignoreAutoGenerated = newValue }
    }

    private init() {
        Settings.migrateLegacyDefaultsIfNeeded()
        d.register(defaults: [
            K.maxItems: 200,
            K.keyCode: Int(kVK_ANSI_E),
            K.mods: Int(cmdKey | shiftKey),
            K.autoPaste: true,
            K.concealed: true,
            K.transient: true,
            K.autoGen: true,
            K.captureSrc: true,
            K.detectRem: true,
            K.transModel: "gpt-4o-mini-transcribe",
            K.geminiModel: "gemini-flash-latest",
            K.transLang: "es",
            K.transVocab: "",
            K.aiProv: "openai",
            K.keyCode2: Int(kVK_ANSI_I),
            K.mods2: Int(cmdKey | shiftKey),
            K.keyCode3: Int(kVK_ANSI_U),
            K.mods3: Int(cmdKey | shiftKey),
            K.uiLang: "en"   // English is the base/default UI language (open-source collaboration)
        ])
        maxItems = d.integer(forKey: K.maxItems)
        combo = KeyCombo(keyCode: UInt32(d.integer(forKey: K.keyCode)),
                         carbonModifiers: UInt32(d.integer(forKey: K.mods)))
        autoPaste = d.object(forKey: K.autoPaste) as? Bool ?? true
        ignoreConcealed = d.object(forKey: K.concealed) as? Bool ?? true
        ignoreTransient = d.object(forKey: K.transient) as? Bool ?? true
        ignoreAutoGenerated = d.object(forKey: K.autoGen) as? Bool ?? true
        excludedBundleIDs = d.stringArray(forKey: K.excluded) ?? []
        captureSource = d.object(forKey: K.captureSrc) as? Bool ?? true
        detectRemoteSource = d.object(forKey: K.detectRem) as? Bool ?? true
        transcriptionModel = d.string(forKey: K.transModel) ?? "gpt-4o-mini-transcribe"
        geminiModel = d.string(forKey: K.geminiModel) ?? "gemini-flash-latest"
        transcriptionLanguage = d.string(forKey: K.transLang) ?? "es"
        transcriptionVocabulary = d.string(forKey: K.transVocab) ?? ""
        aiProvider = d.string(forKey: K.aiProv) ?? "openai"
        voiceCombo = KeyCombo(keyCode: UInt32(d.integer(forKey: K.keyCode2)),
                              carbonModifiers: UInt32(d.integer(forKey: K.mods2)))
        captureCombo = KeyCombo(keyCode: UInt32(d.integer(forKey: K.keyCode3)),
                                carbonModifiers: UInt32(d.integer(forKey: K.mods3)))
        uiLanguage = d.string(forKey: K.uiLang) ?? "en"

        // One-time migration: the capture default changed from ⌘⇧2 to ⌘⇧U (⌘⇧2 was hijacked by apps like Loom).
        // For anyone still on the old persisted ⌘⇧2, move them to ⌘⇧U. If the user chose another shortcut, keep it.
        let migCaptureKey = "migratedCaptureToU"
        if !d.bool(forKey: migCaptureKey) {
            if captureCombo == KeyCombo.legacyCaptureCombo { captureCombo = KeyCombo.defaultCaptureCombo }
            d.set(true, forKey: migCaptureKey)
        }
    }

    func addExcludedApp(_ id: String) {
        guard !id.isEmpty, !excludedBundleIDs.contains(id) else { return }
        excludedBundleIDs.append(id)
    }

    func removeExcludedApp(_ id: String) {
        excludedBundleIDs.removeAll { $0 == id }
    }

    // MARK: - Migration from the old domain (Pasta → Klip)

    private static let migratedFlagKey = "migratedFromPastaClip"

    private static func migrateLegacyDefaultsIfNeeded() {
        let std = UserDefaults.standard
        guard !std.bool(forKey: migratedFlagKey) else { return }
        defer { std.set(true, forKey: migratedFlagKey) }
        guard let legacy = UserDefaults(suiteName: "com.proper.pastaclip") else { return }
        // We don't migrate the shortcut (we want the new ⌃⇧V as the default) or didAutoEnableLogin
        // (Klip registers itself under its new identity).
        let keys = [K.maxItems, K.autoPaste, K.concealed, K.transient, K.autoGen, K.excluded]
        for key in keys {
            if let value = legacy.object(forKey: key), std.object(forKey: key) == nil {
                std.set(value, forKey: key)
            }
        }
    }
}
