import AppKit
import Carbon.HIToolbox
import Combine

// MARK: - Tipos de marcador de privacidad del portapapeles (convención de nspasteboard.com)

enum PasteboardPrivacyTypes {
    static let concealed     = NSPasteboard.PasteboardType("org.nspasteboard.ConcealedType")
    static let transient     = NSPasteboard.PasteboardType("org.nspasteboard.TransientType")
    static let autoGenerated = NSPasteboard.PasteboardType("org.nspasteboard.AutoGeneratedType")
}

// MARK: - Combinación de teclas del atajo global (en espacio Carbon)

struct KeyCombo: Equatable {
    var keyCode: UInt32
    var carbonModifiers: UInt32

    // Los valores por defecto son ⌥⇧ (Option+Shift) + una letra, agrupados por función a la izquierda del teclado por comodidad:
    // E historial · R grabar · D dibujar/anotar · F texto rápido (OCR) · O subir. ⌥⇧ es fácil de mantener pulsado y rara vez es
    // acelerador de app, así que el atajo global de Carbon se dispara; se evita ⌘⇧+letra (acaparado por VS Code/navegadores).
    static let defaultCombo = KeyCombo(keyCode: UInt32(kVK_ANSI_E), carbonModifiers: UInt32(optionKey | shiftKey))            // ⌥⇧E historial
    static let defaultVoiceCombo = KeyCombo(keyCode: UInt32(kVK_ANSI_R), carbonModifiers: UInt32(optionKey | shiftKey))       // ⌥⇧R grabar
    static let defaultCaptureCombo = KeyCombo(keyCode: UInt32(kVK_ANSI_D), carbonModifiers: UInt32(optionKey | shiftKey))     // ⌥⇧D dibujar/anotar
    static let defaultTextCaptureCombo = KeyCombo(keyCode: UInt32(kVK_ANSI_F), carbonModifiers: UInt32(optionKey | shiftKey)) // ⌥⇧F OCR rápido
    static let defaultUploadCombo = KeyCombo(keyCode: UInt32(kVK_ANSI_O), carbonModifiers: UInt32(optionKey | shiftKey))      // ⌥⇧O subir

    // Antiguos valores por defecto ⌥⌘ y el breve set ⌥⇧ Y/R/T/G/E — migrar a quien siga en ellos al set nuevo.
    static let prevOptCmdPanel   = KeyCombo(keyCode: UInt32(kVK_ANSI_Y), carbonModifiers: UInt32(cmdKey | optionKey))
    static let prevOptCmdVoice   = KeyCombo(keyCode: UInt32(kVK_ANSI_R), carbonModifiers: UInt32(cmdKey | optionKey))
    static let prevOptCmdCapture = KeyCombo(keyCode: UInt32(kVK_ANSI_T), carbonModifiers: UInt32(cmdKey | optionKey))
    static let prevOptCmdUpload  = KeyCombo(keyCode: UInt32(kVK_ANSI_G), carbonModifiers: UInt32(cmdKey | optionKey))
    static let prevOptCmdText    = KeyCombo(keyCode: UInt32(kVK_ANSI_E), carbonModifiers: UInt32(cmdKey | optionKey))
    static let prevShiftPanel    = KeyCombo(keyCode: UInt32(kVK_ANSI_Y), carbonModifiers: UInt32(optionKey | shiftKey))
    static let prevShiftCapture  = KeyCombo(keyCode: UInt32(kVK_ANSI_T), carbonModifiers: UInt32(optionKey | shiftKey))
    static let prevShiftUpload   = KeyCombo(keyCode: UInt32(kVK_ANSI_G), carbonModifiers: UInt32(optionKey | shiftKey))
    static let prevShiftText     = KeyCombo(keyCode: UInt32(kVK_ANSI_E), carbonModifiers: UInt32(optionKey | shiftKey))

    // Valores por defecto más antiguos, conservados solo para migrar a quien siga en ellos al set actual (ver migración en init).
    static let legacyPanelCombo   = KeyCombo(keyCode: UInt32(kVK_ANSI_E), carbonModifiers: UInt32(cmdKey | shiftKey)) // ⌘⇧E
    static let legacyVoiceCombo   = KeyCombo(keyCode: UInt32(kVK_ANSI_I), carbonModifiers: UInt32(cmdKey | shiftKey)) // ⌘⇧I
    static let legacyCaptureUCombo = KeyCombo(keyCode: UInt32(kVK_ANSI_U), carbonModifiers: UInt32(cmdKey | shiftKey)) // ⌘⇧U
    // Breves valores por defecto interinos (⌥⌘V panel, ⌥⌘S captura) publicados antes de Y/T — migrarlos hacia adelante también.
    static let interimPanelCombo   = KeyCombo(keyCode: UInt32(kVK_ANSI_V), carbonModifiers: UInt32(cmdKey | optionKey)) // ⌥⌘V
    static let interimCaptureCombo = KeyCombo(keyCode: UInt32(kVK_ANSI_S), carbonModifiers: UInt32(cmdKey | optionKey)) // ⌥⌘S
    /// El valor por defecto de captura más antiguo (⌘⇧2), aún se migra hacia adelante.
    static let legacyCaptureCombo = KeyCombo(keyCode: UInt32(kVK_ANSI_2),
                                             carbonModifiers: UInt32(cmdKey | shiftKey))

    var isValid: Bool { carbonModifiers != 0 }

    var displayString: String {
        var s = ""
        if carbonModifiers & UInt32(controlKey) != 0 { s += "⌃" }
        if carbonModifiers & UInt32(optionKey)  != 0 { s += "⌥" }
        if carbonModifiers & UInt32(shiftKey)   != 0 { s += "⇧" }
        if carbonModifiers & UInt32(cmdKey)     != 0 { s += "⌘" }
        s += KeyCombo.keyName(for: keyCode)
        return s
    }

    static func keyName(for keyCode: UInt32) -> String {
        let map: [UInt32: String] = [
            UInt32(kVK_ANSI_A): "A", UInt32(kVK_ANSI_B): "B", UInt32(kVK_ANSI_C): "C",
            UInt32(kVK_ANSI_D): "D", UInt32(kVK_ANSI_E): "E", UInt32(kVK_ANSI_F): "F",
            UInt32(kVK_ANSI_G): "G", UInt32(kVK_ANSI_H): "H", UInt32(kVK_ANSI_I): "I",
            UInt32(kVK_ANSI_J): "J", UInt32(kVK_ANSI_K): "K", UInt32(kVK_ANSI_L): "L",
            UInt32(kVK_ANSI_M): "M", UInt32(kVK_ANSI_N): "N", UInt32(kVK_ANSI_O): "O",
            UInt32(kVK_ANSI_P): "P", UInt32(kVK_ANSI_Q): "Q", UInt32(kVK_ANSI_R): "R",
            UInt32(kVK_ANSI_S): "S", UInt32(kVK_ANSI_T): "T", UInt32(kVK_ANSI_U): "U",
            UInt32(kVK_ANSI_V): "V", UInt32(kVK_ANSI_W): "W", UInt32(kVK_ANSI_X): "X",
            UInt32(kVK_ANSI_Y): "Y", UInt32(kVK_ANSI_Z): "Z",
            UInt32(kVK_ANSI_0): "0", UInt32(kVK_ANSI_1): "1", UInt32(kVK_ANSI_2): "2",
            UInt32(kVK_ANSI_3): "3", UInt32(kVK_ANSI_4): "4", UInt32(kVK_ANSI_5): "5",
            UInt32(kVK_ANSI_6): "6", UInt32(kVK_ANSI_7): "7", UInt32(kVK_ANSI_8): "8",
            UInt32(kVK_ANSI_9): "9",
            UInt32(kVK_Space): "Space", UInt32(kVK_Return): "↩", UInt32(kVK_Tab): "⇥",
            UInt32(kVK_Escape): "⎋", UInt32(kVK_Delete): "⌫",
            UInt32(kVK_ANSI_Period): ".", UInt32(kVK_ANSI_Comma): ",",
            UInt32(kVK_ANSI_Slash): "/", UInt32(kVK_ANSI_Semicolon): ";"
        ]
        return map[keyCode] ?? String(format: "Key %02X", keyCode)
    }

    /// Combinaciones sugeridas para elegir sin grabar (se muestran en Preferencias). Empieza con combos ⌥⌘, que
    /// rara vez chocan con aceleradores de apps (así el atajo global se dispara de forma fiable); las opciones ⌘⇧ van después.
    static let suggestions: [KeyCombo] = [
        KeyCombo(keyCode: UInt32(kVK_ANSI_Y), carbonModifiers: UInt32(optionKey | shiftKey)),  // ⌥⇧Y (panel)
        KeyCombo(keyCode: UInt32(kVK_ANSI_R), carbonModifiers: UInt32(optionKey | shiftKey)),  // ⌥⇧R (voz)
        KeyCombo(keyCode: UInt32(kVK_ANSI_T), carbonModifiers: UInt32(optionKey | shiftKey)),  // ⌥⇧T (captura)
        KeyCombo(keyCode: UInt32(kVK_ANSI_G), carbonModifiers: UInt32(optionKey | shiftKey)),  // ⌥⇧G
        KeyCombo(keyCode: UInt32(kVK_ANSI_K), carbonModifiers: UInt32(optionKey | shiftKey)),  // ⌥⇧K
        KeyCombo(keyCode: UInt32(kVK_ANSI_J), carbonModifiers: UInt32(optionKey | shiftKey)),  // ⌥⇧J
        KeyCombo(keyCode: UInt32(kVK_Space),  carbonModifiers: UInt32(optionKey)),           // ⌥Space
        KeyCombo(keyCode: UInt32(kVK_ANSI_M), carbonModifiers: UInt32(cmdKey | shiftKey))    // ⌘⇧M
    ]
}

func cocoaToCarbonModifiers(_ flags: NSEvent.ModifierFlags) -> UInt32 {
    var carbon: UInt32 = 0
    if flags.contains(.command) { carbon |= UInt32(cmdKey) }
    if flags.contains(.shift)   { carbon |= UInt32(shiftKey) }
    if flags.contains(.option)  { carbon |= UInt32(optionKey) }
    if flags.contains(.control) { carbon |= UInt32(controlKey) }
    return carbon
}

// MARK: - Almacén de ajustes (UserDefaults), única fuente de verdad

final class Settings: ObservableObject {
    static let shared = Settings()
    private let d = UserDefaults.standard

    /// Bandera de onboarding de primera ejecución (ver WelcomeView). UserDefaults simple — no hace falta publicarla.
    var hasSeenWelcome: Bool {
        get { d.bool(forKey: "hasSeenWelcome") }
        set { d.set(newValue, forKey: "hasSeenWelcome") }
    }

    private enum K {
        static let maxItems   = "maxItems"
        static let keyCode    = "hotKeyCode"
        static let mods       = "hotKeyModifiers"
        static let autoPaste  = "autoPaste"
        static let concealed  = "privacy.ignoreConcealed"
        static let transient  = "privacy.ignoreTransient"
        static let autoGen    = "privacy.ignoreAutoGenerated"
        static let excluded   = "privacy.excludedBundleIDs"
        static let captureSrc = "captureSource"
        static let cleanCap   = "cleanCapture"
        static let detectRem  = "detectRemoteSource"
        static let transModel = "transcriptionModel"
        static let geminiModel = "geminiModel"
        static let transLang  = "transcriptionLanguage"
        static let transVocab = "transcriptionVocabulary"
        static let localModel = "localModel"
        static let aiProv     = "aiProvider"
        static let keyCode2   = "voiceHotKeyCode"
        static let mods2      = "voiceHotKeyModifiers"
        static let keyCode3   = "captureHotKeyCode"
        static let mods3      = "captureHotKeyModifiers"
        static let keyCode4   = "uploadHotKeyCode"
        static let mods4      = "uploadHotKeyModifiers"
        static let keyCode5   = "textCaptureHotKeyCode"
        static let mods5      = "textCaptureHotKeyModifiers"
        static let uiLang     = "uiLanguage"
    }

    @Published var maxItems: Int          { didSet { d.set(maxItems, forKey: K.maxItems) } }
    @Published var combo: KeyCombo        { didSet {
        d.set(Int(combo.keyCode), forKey: K.keyCode)
        d.set(Int(combo.carbonModifiers), forKey: K.mods)
    } }
    @Published var autoPaste: Bool        { didSet { d.set(autoPaste, forKey: K.autoPaste) } }
    @Published var ignoreConcealed: Bool  { didSet { d.set(ignoreConcealed, forKey: K.concealed) } }
    @Published var ignoreTransient: Bool  { didSet { d.set(ignoreTransient, forKey: K.transient) } }
    @Published var ignoreAutoGenerated: Bool { didSet { d.set(ignoreAutoGenerated, forKey: K.autoGen) } }
    @Published var excludedBundleIDs: [String] { didSet { d.set(excludedBundleIDs, forKey: K.excluded) } }
    @Published var captureSource: Bool    { didSet { d.set(captureSource, forKey: K.captureSrc) } }
    /// "Pegar siempre limpio": guarda las copias con formato como Markdown limpio (mantiene negritas/cursivas + emojis, descarta estilos).
    @Published var cleanCapture: Bool     { didSet { d.set(cleanCapture, forKey: K.cleanCap) } }
    @Published var detectRemoteSource: Bool { didSet { d.set(detectRemoteSource, forKey: K.detectRem) } }
    @Published var transcriptionModel: String { didSet { d.set(transcriptionModel, forKey: K.transModel) } }
    /// Modelo de Google Gemini para transcripción (configurable; antes fijado en código a "gemini-flash-latest").
    @Published var geminiModel: String { didSet { d.set(geminiModel, forKey: K.geminiModel) } }
    @Published var transcriptionLanguage: String { didSet { d.set(transcriptionLanguage, forKey: K.transLang) } }
    /// Palabras de contexto / vocabulario (nombres, marcas, jerga) enviadas al transcriptor para que las escriba bien.
    @Published var transcriptionVocabulary: String { didSet { d.set(transcriptionVocabulary, forKey: K.transVocab) } }
    /// Nombre del modelo en el dispositivo (WhisperKit) cuando aiProvider == "local".
    @Published var localModel: String { didSet { d.set(localModel, forKey: K.localModel) } }
    /// Proveedor de IA para transcripción: "local" (en el dispositivo), "openai" o "gemini".
    @Published var aiProvider: String { didSet { d.set(aiProvider, forKey: K.aiProv) } }
    @Published var voiceCombo: KeyCombo   { didSet {
        d.set(Int(voiceCombo.keyCode), forKey: K.keyCode2)
        d.set(Int(voiceCombo.carbonModifiers), forKey: K.mods2)
    } }
    @Published var captureCombo: KeyCombo { didSet {
        d.set(Int(captureCombo.keyCode), forKey: K.keyCode3)
        d.set(Int(captureCombo.carbonModifiers), forKey: K.mods3)
    } }
    /// Atajo global para abrir la ventana "Subir audio para transcribir".
    @Published var uploadCombo: KeyCombo  { didSet {
        d.set(Int(uploadCombo.keyCode), forKey: K.keyCode4)
        d.set(Int(uploadCombo.carbonModifiers), forKey: K.mods4)
    } }
    /// Atajo global para capturar una región y extraer su texto directo al portapapeles (OCR, sin editor).
    @Published var textCaptureCombo: KeyCombo { didSet {
        d.set(Int(textCaptureCombo.keyCode), forKey: K.keyCode5)
        d.set(Int(textCaptureCombo.carbonModifiers), forKey: K.mods5)
    } }
    @Published var uiLanguage: String     { didSet {
        d.set(uiLanguage, forKey: K.uiLang)
        // Mantiene el idioma de audio siguiendo al idioma de la plataforma, pero SOLO mientras el usuario no
        // haya divergido deliberadamente: sincroniza solo si aún seguía el idioma de UI anterior. Esto nunca
        // sobrescribe una elección explícita (incluido "" = autodetección).
        if uiLanguage != oldValue, transcriptionLanguage == oldValue { transcriptionLanguage = uiLanguage }
    } }

    /// Interruptor simple que controla los tres filtros de privacidad a la vez.
    var ignoreSensitive: Bool {
        get { ignoreConcealed || ignoreTransient || ignoreAutoGenerated }
        set { ignoreConcealed = newValue; ignoreTransient = newValue; ignoreAutoGenerated = newValue }
    }

    private init() {
        Settings.migrateLegacyDefaultsIfNeeded()
        d.register(defaults: [
            K.maxItems: 200,
            K.keyCode: Int(kVK_ANSI_E),
            K.mods: Int(optionKey | shiftKey),
            K.autoPaste: true,
            K.concealed: true,
            K.transient: true,
            K.autoGen: true,
            K.captureSrc: true,
            K.cleanCap: true,
            K.detectRem: true,
            K.transModel: "gpt-4o-mini-transcribe",
            K.geminiModel: "gemini-flash-latest",
            K.transLang: "es",
            K.transVocab: "",
            K.localModel: "small",   // mejor equilibrio precisión/velocidad en Apple Silicon (descarga ~480 MB una sola vez)
            K.aiProv: "local",   // en el dispositivo (WhisperKit) por defecto; la nube es opcional (requiere una API key)
            K.keyCode2: Int(kVK_ANSI_R),
            K.mods2: Int(optionKey | shiftKey),
            K.keyCode3: Int(kVK_ANSI_D),
            K.mods3: Int(optionKey | shiftKey),
            K.keyCode4: Int(kVK_ANSI_O),
            K.mods4: Int(optionKey | shiftKey),
            K.keyCode5: Int(kVK_ANSI_F),
            K.mods5: Int(optionKey | shiftKey),
            K.uiLang: "en"   // El inglés es el idioma de UI base/por defecto (colaboración open source)
        ])
        maxItems = d.integer(forKey: K.maxItems)
        combo = KeyCombo(keyCode: UInt32(d.integer(forKey: K.keyCode)),
                         carbonModifiers: UInt32(d.integer(forKey: K.mods)))
        autoPaste = d.object(forKey: K.autoPaste) as? Bool ?? true
        ignoreConcealed = d.object(forKey: K.concealed) as? Bool ?? true
        ignoreTransient = d.object(forKey: K.transient) as? Bool ?? true
        ignoreAutoGenerated = d.object(forKey: K.autoGen) as? Bool ?? true
        excludedBundleIDs = d.stringArray(forKey: K.excluded) ?? []
        captureSource = d.object(forKey: K.captureSrc) as? Bool ?? true
        cleanCapture = d.object(forKey: K.cleanCap) as? Bool ?? true
        detectRemoteSource = d.object(forKey: K.detectRem) as? Bool ?? true
        transcriptionModel = d.string(forKey: K.transModel) ?? "gpt-4o-mini-transcribe"
        geminiModel = d.string(forKey: K.geminiModel) ?? "gemini-flash-latest"
        transcriptionLanguage = d.string(forKey: K.transLang) ?? "es"
        transcriptionVocabulary = d.string(forKey: K.transVocab) ?? ""
        localModel = d.string(forKey: K.localModel) ?? "small"
        aiProvider = d.string(forKey: K.aiProv) ?? "local"
        voiceCombo = KeyCombo(keyCode: UInt32(d.integer(forKey: K.keyCode2)),
                              carbonModifiers: UInt32(d.integer(forKey: K.mods2)))
        captureCombo = KeyCombo(keyCode: UInt32(d.integer(forKey: K.keyCode3)),
                                carbonModifiers: UInt32(d.integer(forKey: K.mods3)))
        uploadCombo = KeyCombo(keyCode: UInt32(d.integer(forKey: K.keyCode4)),
                               carbonModifiers: UInt32(d.integer(forKey: K.mods4)))
        textCaptureCombo = KeyCombo(keyCode: UInt32(d.integer(forKey: K.keyCode5)),
                                    carbonModifiers: UInt32(d.integer(forKey: K.mods5)))
        uiLanguage = d.string(forKey: K.uiLang) ?? "en"

        // Migración única: el valor por defecto de captura cambió de ⌘⇧2 a ⌘⇧U (⌘⇧2 lo secuestraban apps como Loom).
        // A quien siga con el viejo ⌘⇧2 persistido, moverlo a ⌘⇧U. Si el usuario eligió otro atajo, se conserva.
        let migCaptureKey = "migratedCaptureToU"
        if !d.bool(forKey: migCaptureKey) {
            if captureCombo == KeyCombo.legacyCaptureCombo { captureCombo = KeyCombo.legacyCaptureUCombo }
            d.set(true, forKey: migCaptureKey)
        }

        // Migración única de los atajos por defecto al set ⌥⌘ actual con letras poco comunes
        // (panel ⌥⌘Y · voz ⌥⌘R · captura ⌥⌘T). Atrapa TANTO los defaults originales ⌘⇧E/⌘⇧I/⌘⇧U como los
        // breves defaults interinos ⌥⌘V/⌥⌘S. Quien eligió su propio combo lo conserva. Usa una bandera nueva (V3)
        // para que los usuarios que ya corrieron el build interino también avancen. Debe correr DESPUÉS de
        // migratedCaptureToU para que un default de captura ⌘⇧2 llegue aquí como ⌘⇧U y luego avance a ⌥⌘T.
        let migHotkeysV3 = "migratedHotkeysV3"
        if !d.bool(forKey: migHotkeysV3) {
            if combo == KeyCombo.legacyPanelCombo || combo == KeyCombo.interimPanelCombo { combo = KeyCombo.defaultCombo }
            if voiceCombo == KeyCombo.legacyVoiceCombo { voiceCombo = KeyCombo.defaultVoiceCombo }
            if captureCombo == KeyCombo.legacyCaptureUCombo || captureCombo == KeyCombo.interimCaptureCombo { captureCombo = KeyCombo.defaultCaptureCombo }
            d.set(true, forKey: migHotkeysV3)
        }

        // Migración única de los defaults ⌥⌘ al nuevo set ⌥⇧ (⌥⌘ era incómodo de pulsar). Quien siga
        // en un default ⌥⌘ se traslada; un combo personalizado se conserva.
        let migHotkeysV4 = "migratedHotkeysV4"
        if !d.bool(forKey: migHotkeysV4) {
            if combo == KeyCombo.prevOptCmdPanel { combo = KeyCombo.defaultCombo }
            if voiceCombo == KeyCombo.prevOptCmdVoice { voiceCombo = KeyCombo.defaultVoiceCombo }
            if captureCombo == KeyCombo.prevOptCmdCapture { captureCombo = KeyCombo.defaultCaptureCombo }
            if uploadCombo == KeyCombo.prevOptCmdUpload { uploadCombo = KeyCombo.defaultUploadCombo }
            if textCaptureCombo == KeyCombo.prevOptCmdText { textCaptureCombo = KeyCombo.defaultTextCaptureCombo }
            d.set(true, forKey: migHotkeysV4)
        }

        // Migración de reletrado: el breve set ⌥⇧ Y/T/G/E → el set E/R/D/F/O agrupado por función (voz ⌥⇧R se mantiene).
        let migHotkeysV5 = "migratedHotkeysV5"
        if !d.bool(forKey: migHotkeysV5) {
            if combo == KeyCombo.prevShiftPanel { combo = KeyCombo.defaultCombo }                       // ⌥⇧Y → ⌥⇧E
            if captureCombo == KeyCombo.prevShiftCapture { captureCombo = KeyCombo.defaultCaptureCombo } // ⌥⇧T → ⌥⇧D
            if uploadCombo == KeyCombo.prevShiftUpload { uploadCombo = KeyCombo.defaultUploadCombo }     // ⌥⇧G → ⌥⇧O
            if textCaptureCombo == KeyCombo.prevShiftText { textCaptureCombo = KeyCombo.defaultTextCaptureCombo } // ⌥⇧E → ⌥⇧F
            d.set(true, forKey: migHotkeysV5)
        }

        // Migración única a transcripción en el dispositivo (el nuevo valor por defecto). Los usuarios de nube existentes
        // son anteriores a la opción "local"; moverlos a local una vez para que la transcripción funcione offline sin API key.
        // Reversible: pueden volver a elegir OpenAI/Gemini en Preferencias (y no serán migrados de nuevo).
        let migLocalKey = "migratedToLocalProvider"
        if !d.bool(forKey: migLocalKey) {
            aiProvider = "local"
            d.set(true, forKey: migLocalKey)
        }
    }

    func addExcludedApp(_ id: String) {
        guard !id.isEmpty, !excludedBundleIDs.contains(id) else { return }
        excludedBundleIDs.append(id)
    }

    func removeExcludedApp(_ id: String) {
        excludedBundleIDs.removeAll { $0 == id }
    }

    // MARK: - Migración desde el dominio antiguo (Pasta → Klip)

    private static let migratedFlagKey = "migratedFromPastaClip"

    private static func migrateLegacyDefaultsIfNeeded() {
        let std = UserDefaults.standard
        guard !std.bool(forKey: migratedFlagKey) else { return }
        defer { std.set(true, forKey: migratedFlagKey) }
        guard let legacy = UserDefaults(suiteName: "com.proper.pastaclip") else { return }
        // No migramos los atajos (Klip usa sus propios defaults: ⌘⇧E / ⌘⇧I / ⌘⇧U) ni didAutoEnableLogin
        // (Klip se registra bajo su nueva identidad).
        let keys = [K.maxItems, K.autoPaste, K.concealed, K.transient, K.autoGen, K.excluded]
        for key in keys {
            if let value = legacy.object(forKey: key), std.object(forKey: key) == nil {
                std.set(value, forKey: key)
            }
        }
    }
}

/// Idiomas de audio/dictado ofrecidos al transcriptor (endónimos), compartidos por Preferencias y la ventana
/// de Subida. "" (autodetección) se añade en la capa de UI vía la cadena "lang.auto".
enum DictationLanguage {
    static let all: [(code: String, name: String)] = [
        ("en", "English"), ("es", "Español"), ("fr", "Français"), ("de", "Deutsch"),
        ("it", "Italiano"), ("pt", "Português"), ("zh", "中文"), ("ja", "日本語"),
        ("ko", "한국어"), ("ru", "Русский"), ("nl", "Nederlands"), ("hi", "हिन्दी")
    ]
}
